import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './_scrollbar.scss'
import ToastContainer from './components/toast'
import AuthContext from './providers'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthContext>{children}</AuthContext>
        <ToastContainer />
      </body>
    </html>
  )
}
