import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './_scrollbar.scss'
import ToastContainer from './components/toast'
import AuthContext from './providers'
import QueryProviders from './reactQueryProviders'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: '%s | Organick',
  description: 'Generated by NNT',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
      </head>
      <body className={inter.className}>
        <QueryProviders>
          <AuthContext>{children}</AuthContext>
          <ToastContainer />
        </QueryProviders>
      </body>
    </html>
  )
}
