import Footer from '@/app/components/footer'
import Header from '@/app/components/header'
import NewLatter from '@/app/components/newslatter'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AOSComponent from '../components/aos'
import './_index.scss'
const inter = Inter({ subsets: ['latin'] })
config.autoAddCss = false
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <AOSComponent>{children}</AOSComponent>
      <NewLatter />
    </>
  )
}
