import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import 'bootstrap/dist/css/bootstrap.css'
import '@/app/(client)/_index.scss'
import ChatWrapper from './ChatWrapper'
import Footer from '@/app/components/footer'
import Header from '@/app/components/header'
import NewLatter from '@/app/components/newslatter'
import AOSComponent from '../components/aos'

const inter = Inter({ subsets: ['latin'] })
config.autoAddCss = false

export const metadata: Metadata = {
  title: {
    template: '%s | Organick',
    default: 'Organick',
  },
  description: 'Generated by NNT',
}

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <AOSComponent>{children}</AOSComponent>
      <NewLatter />
      <Footer />
      <ChatWrapper />
    </>
  )
}
